apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-demo
  template:
    metadata:
      labels:
        app: alpine-demo
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: alpine
        image: 10.109.234.52/demo/alpine:latest
        command: 
        - sh
        - -c
        - echo "Alpine from Harbor is running!" && sleep 3600
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          runAsUser: 1000