apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-demo
  namespace: default
  labels:
    app: alpine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-demo
  template:
    metadata:
      labels:
        app: alpine-demo
    spec:
      imagePullSecrets:
      - name: harbor-creds
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: alpine
        image: 100.100.2.75:30443/demo/alpine:latest
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - echo "Alpine from Harbor is running!" && sleep 3600
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          runAsUser: 1000