apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: harbor-ca
  secretName: harbor-ca-secret
  ipAddresses:
  - 100.100.2.75
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer